[project]
name = "python-picnic-api2"
version = "2.0.1"
description = ""
readme = "README.md"
license = {text = "Apache-2.0"}
maintainers = [
  { name = "CodeSalat", email = "pypi@codesalat.dev"}
]
authors = [
  { name = "Mike Brink", email = "mjh.brink@icloud.com"},
  { name = "CodeSalat", email = "pypi@codesalat.dev"}
]
urls = {homepage = "https://github.com/codesalatdev/python-picnic-api", repository = "https://github.com/codesalatdev/python-picnic-api"}
requires-python = ">=3.13"
dependencies = [
  "requests>=2.34.2",
  "typing_extensions>=4.16.0",
  "pydantic>=2.13.4"
]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
  # flake8-fixme
  "FIX"
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.16.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
